const Contact =()=>{
    return(
        <div id="contact">
            <h1 className="bg-yellow-200 text-2xl font-bold p-2">Contact</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, aliquid? Tempora minus sunt blanditiis, ipsa dicta repudiandae placeat perferendis consequuntur perspiciatis ullam impedit. Odio a tenetur eum sit iste dicta! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo repellat deleniti laudantium. Nihil asperiores a, aspernatur est dolorum dolor dignissimos facere reiciendis consequatur sed incidunt eveniet, commodi exercitationem cupiditate alias?
            Porro, ad minus excepturi suscipit libero maiores harum quod ea quas quo, non sit nulla sed tenetur debitis commodi possimus repellat repudiandae! Fugit corporis nam, esse commodi tempora ut animi?
            Minus libero sunt quidem laudantium atque odit, corporis quo itaque reiciendis. Ea necessitatibus asperiores nemo. Exercitationem possimus voluptatum recusandae rerum, nesciunt, molestias harum necessitatibus at alias quas rem. Dicta, sint.
            Corporis voluptatibus, ex, repudiandae sit excepturi fuga laborum alias maiores maxime ad magnam nulla, incidunt dignissimos assumenda officia nihil! Recusandae adipisci assumenda minima veritatis animi corporis quidem alias molestiae et!
            Delectus mollitia itaque asperiores voluptas soluta eos dolores! Omnis, earum! Ad tempore, eum, tempora dolorum et natus culpa omnis, alias rem asperiores voluptates non sequi totam repellendus ipsam earum facilis.
            Possimus ullam id enim earum, distinctio ducimus mollitia perspiciatis expedita soluta atque, necessitatibus corrupti doloremque rem aut, iusto recusandae doloribus ipsa voluptatibus quos amet minus qui. Beatae explicabo esse hic.
            Commodi enim tempore, beatae amet libero repellendus harum quod quis temporibus expedita, quisquam vero ea delectus magni porro dolore ipsa voluptatibus perferendis. Eveniet neque dicta repellat error libero odio sint?
            Ducimus illum quasi architecto illo dolorum quam ullam soluta aliquam delectus dolor rem vitae, labore cum, libero iste, laboriosam magnam eveniet necessitatibus optio? Nesciunt ipsum excepturi, placeat nostrum reiciendis quis.
            Nulla officia ullam, explicabo error odio commodi quisquam maxime dolorem ducimus qui harum aspernatur voluptatum repudiandae. Porro labore ut ex quasi eum, cum, natus odit doloremque ullam ipsum ad fugiat.
            Est, recusandae assumenda iure excepturi tempore, in eaque libero similique aspernatur, doloribus numquam vel. Perferendis in cupiditate et quos neque velit odio vitae distinctio nam ad error, possimus est enim!
            Recusandae quae veritatis sapiente incidunt doloremque sed pariatur fuga quia dolores alias iusto saepe praesentium voluptate cum commodi ad qui eligendi autem illum, nesciunt unde labore mollitia? Enim, fugit suscipit.
            Fuga fugiat deleniti harum ea corporis officiis ullam adipisci, quia, unde aliquam rerum non quasi ad eveniet facere at suscipit placeat vitae quaerat. Porro in similique blanditiis ullam error atque.
            Minima aliquid, quis dolore exercitationem voluptatem assumenda, at quod iure harum, voluptate non necessitatibus obcaecati nam sint maiores molestiae! Maiores tempore suscipit corrupti hic possimus optio officiis ratione fugit blanditiis!
            Amet repellendus maiores voluptates ducimus dolorum doloremque culpa, labore facere nisi error aperiam commodi! Nam, nemo illum totam incidunt doloribus repudiandae esse veniam dolore, cupiditate reprehenderit consequatur ipsum et a.
            Animi tenetur iure tempore, fugiat vel, eius laboriosam ut aliquid nulla sunt veritatis modi ipsum optio fuga accusantium voluptatem, perspiciatis suscipit? Ullam, sit voluptatum recusandae hic culpa repellendus suscipit debitis!
            Magnam aperiam natus repellat quisquam reprehenderit expedita assumenda ipsa porro tempora quos maxime molestias, minima eius numquam aliquam soluta sit, rem quam. Eos dolore temporibus enim, facilis amet tempora atque?
            Soluta voluptatibus maxime, necessitatibus perferendis ipsam consectetur harum est, voluptatum quasi accusantium dolores alias quod? Eveniet deleniti, aliquam, atque, facilis nesciunt quasi aspernatur eaque ea vel eum consequatur ullam qui.
            Omnis ut alias expedita nihil quibusdam corrupti assumenda enim? Dolor, itaque nemo! Officia dolorum culpa vero numquam deleniti voluptas corrupti corporis expedita? Non, amet nam modi quis doloribus nisi mollitia.
            Veniam odio dolore, eveniet excepturi iste magni velit rerum voluptatum beatae aliquam sit fugit, soluta, itaque aut unde omnis assumenda quis laborum officia. Facilis rem accusantium enim, tempore iste exercitationem!
            Aliquid nobis minima sapiente error perferendis voluptatem deleniti alias corrupti hic quo natus quam eligendi dolorem iure, optio fuga libero sit laudantium. Esse adipisci ducimus, accusantium eum porro sint voluptatem!
            Placeat, numquam. Provident numquam modi architecto eligendi magnam at, voluptate excepturi dolores perferendis, praesentium nisi minima, non similique! Animi accusamus quia tempore dolorum alias cumque quasi est tempora soluta ab.
            Ipsum in saepe iusto atque, obcaecati cum reprehenderit, alias voluptatibus commodi laudantium ad illum minima nostrum eum vero, incidunt possimus iste quas eaque quis libero! Voluptatum similique culpa eos praesentium!
            Quas doloremque rem, quis, accusantium facere, eius voluptates dolor cum nostrum laborum numquam dolorem quibusdam! Sed saepe ipsum sint totam exercitationem dicta ipsa facilis veniam sit odit cumque, quod quia.
            Expedita inventore porro aut provident cum sed quaerat, tenetur vero. Excepturi iste, ipsa eveniet culpa minima tenetur esse itaque autem! Quo dolorum voluptatem voluptates cum distinctio adipisci, rem veritatis accusantium.
            Rem culpa omnis tempore fuga ut rerum maiores commodi cum, nisi at aliquid cumque doloremque corrupti excepturi? Exercitationem, consectetur iste, tenetur error repellendus dignissimos cum inventore earum praesentium minus doloremque.
            Harum voluptas explicabo sed distinctio minus numquam, quas molestiae error exercitationem iure modi accusamus pariatur laudantium cumque illum aliquid reprehenderit nemo debitis incidunt adipisci. Architecto voluptates autem commodi tempore necessitatibus.
            Facilis dolorem minus, ullam deleniti necessitatibus dolor nihil cupiditate sunt provident corporis! Quia quos quaerat est veniam, voluptates fuga incidunt earum quod pariatur ab, iusto eveniet! Quod quis nulla perferendis.
            Nemo doloremque ea mollitia ex nostrum aliquid, quasi debitis assumenda obcaecati, praesentium laboriosam reiciendis, non recusandae. Repellendus nesciunt veniam dolores, amet nam quis at et praesentium, itaque doloribus inventore delectus?
            Quia natus corrupti odio excepturi corporis repellendus eligendi aperiam suscipit dolorem tempore commodi sint doloremque deserunt assumenda ratione, illum eum atque nisi animi dignissimos. Distinctio quod molestiae architecto accusantium aliquam?
            Officia assumenda enim exercitationem hic necessitatibus ea, ratione delectus recusandae, id magni excepturi, ab minima ut. Doloremque voluptas minus mollitia quam! Eveniet fugiat delectus enim quam obcaecati iste voluptatem necessitatibus.
            Impedit, dicta fugiat? Quasi quo commodi nostrum molestias atque laboriosam culpa eius, sequi sit debitis dolorem esse recusandae quam ipsam inventore eveniet architecto animi doloribus ipsa rem dolorum praesentium. Consectetur.
            Totam voluptatem reiciendis iste aliquam sapiente mollitia dignissimos, quis commodi eum molestias similique autem eveniet nam, illo, quos ut esse corporis ab voluptate harum perspiciatis sit. Totam autem quas nisi.
            Ipsa molestiae odio, veritatis explicabo exercitationem autem qui culpa repellat libero rerum distinctio cum deserunt optio tempora iure eligendi? Quo libero perspiciatis maiores assumenda nulla deleniti facilis veritatis vero temporibus.
            Quasi eligendi atque nobis fugiat sint vitae id quidem quo cumque! Repudiandae aperiam necessitatibus temporibus, quasi cum exercitationem! Labore quaerat ratione obcaecati. Cumque eos temporibus quos magni corrupti nam nulla?
            Repellat, repudiandae. Praesentium cupiditate necessitatibus explicabo officia eum maiores molestias corrupti ea vero fugit consequatur fuga, dolores, eveniet provident blanditiis ducimus accusamus corporis enim rerum magnam possimus? Mollitia, nihil laboriosam.
            Excepturi quidem nihil facilis sequi repudiandae? Pariatur labore nihil quas eum rerum impedit distinctio voluptatum dolorem, et alias est eos tempora non harum adipisci. Ullam cupiditate optio accusantium maiores corporis?
            Fuga cupiditate dolores blanditiis quas. Odio corrupti placeat accusantium, quo magni fuga neque deleniti fugit ipsa quia magnam eum odit asperiores natus mollitia optio cumque dolores assumenda quam. Odit, enim?
            Dicta nihil molestias temporibus quos id saepe corrupti reiciendis aliquam nobis, odit deleniti vero corporis similique, iure assumenda qui quo in ullam. Voluptatem odit aspernatur debitis repellendus nesciunt? Id, modi?
            Excepturi, deserunt? Quam perspiciatis numquam beatae accusantium magni eius libero, facilis quisquam, consectetur aut inventore, quidem natus odit cumque? Excepturi molestias, vel quo natus at consequatur corrupti reiciendis rem nobis!
            Pariatur officiis maxime a. Corrupti cumque libero sint delectus expedita. Expedita nulla repellendus culpa voluptatibus eos veniam unde hic asperiores voluptatem quos? Eos nihil aspernatur quis dolorum officia veniam deserunt.
            Maxime nisi tempore odio debitis alias voluptate officia aperiam quidem rerum voluptatibus et, hic eveniet aliquid. Fugiat esse quas, facilis laudantium sed nisi temporibus odit ducimus quam eveniet nulla commodi!
            Optio quia doloribus facilis mollitia iure architecto dolorem quisquam tempore deserunt sed, ullam ab deleniti illo eaque a aspernatur debitis veniam. Delectus sunt itaque error repellendus fuga illo nam dolorem!
            Voluptas nulla incidunt excepturi illo rem? Accusamus corrupti impedit sit, soluta pariatur voluptate, omnis officia sint facere doloremque obcaecati temporibus aliquid nulla nam. Quasi vero deserunt optio, expedita aliquid architecto!
            Atque cupiditate repudiandae ab itaque, velit debitis odit explicabo eveniet porro ullam saepe! Voluptatum, aliquid libero velit perferendis nostrum quisquam a quo, vero dignissimos, rem cumque sint corrupti veniam animi.
            Velit, placeat aut? Iure, delectus. Exercitationem error officiis, aut accusantium impedit porro velit natus expedita, perspiciatis deleniti et quas ad, inventore quos recusandae. Error fugiat inventore omnis soluta doloribus voluptates!
            Quibusdam, illum assumenda ipsum maxime ducimus necessitatibus culpa eos itaque nemo omnis placeat voluptas sunt? Hic doloribus cum maxime suscipit. Error aperiam mollitia dolor placeat assumenda reiciendis ea ipsum officia?
            Eum nisi, laudantium est voluptatibus dolores culpa tempore dolore officiis excepturi delectus autem impedit neque provident, reprehenderit recusandae quam, repudiandae totam id animi necessitatibus. Saepe autem fuga nesciunt esse eius.
            Minus delectus quisquam sint porro repellendus sapiente maiores sunt magnam ab, neque quidem, rerum recusandae perspiciatis, cum eveniet dolore assumenda atque placeat quas error a. Corporis iure expedita illum velit!
            Id, minus vitae amet expedita accusantium est dignissimos non et ad incidunt dolorum enim! Voluptatem veniam cupiditate vel illo accusamus ipsa illum! Molestiae saepe similique obcaecati, possimus labore illum nisi?
            Similique dolor eius a rem voluptates veritatis laborum odit voluptate quo, molestiae exercitationem laboriosam provident illum eligendi pariatur quibusdam accusantium ea assumenda quasi porro itaque laudantium fuga fugiat quae. Eos.
            Quibusdam officiis, reprehenderit blanditiis hic voluptatem veritatis nostrum quidem minus eum suscipit voluptatibus, dolorem sequi quod exercitationem eius unde dolor nesciunt neque ipsam beatae dolore. Natus est adipisci obcaecati saepe?
            Eum repudiandae aliquid, dolor velit at eaque ipsum voluptates corporis error similique quas, vero, ab consequatur asperiores culpa? Corporis eaque architecto eius. Quasi minima ut incidunt facere non, odit voluptatibus?
            Tenetur officia in magni quia dolores qui dicta quis obcaecati repudiandae esse, molestias aliquam veritatis! Quibusdam, fugiat tempore? Deleniti eligendi reprehenderit voluptatibus adipisci quos alias deserunt modi quia recusandae sunt!
            Esse quaerat, praesentium harum quo error laborum culpa est ipsa hic consequuntur repudiandae dolor quidem repellendus laboriosam molestias porro quibusdam nemo odit, similique necessitatibus voluptates explicabo sequi reprehenderit! Neque, nostrum.
            Possimus vel minima aut, est distinctio cupiditate porro enim voluptatem itaque officiis nesciunt quos! Itaque possimus nesciunt nemo! Rem consequuntur suscipit dignissimos earum illum aperiam incidunt neque illo quasi quo.
            Magnam pariatur aperiam reprehenderit necessitatibus corrupti sequi sed recusandae dolores perspiciatis laborum, eum, optio voluptatibus aspernatur vero accusantium ipsum odit dignissimos! Rem praesentium numquam nam esse beatae, saepe aspernatur quod?
            Minus ea, animi ullam ipsam eos enim iusto atque suscipit porro, nisi mollitia pariatur at officia sapiente. Assumenda facilis dolore, maiores magni, officia corrupti laudantium eaque exercitationem odio facere atque.
            Obcaecati possimus atque, aliquam cumque magni culpa veniam ad laborum error, ullam accusamus aspernatur inventore quis enim, aperiam eius tempora voluptate. Eius ipsum rerum et at cupiditate explicabo corrupti fugiat!
            Ipsum repellat cumque eveniet at dolores itaque ea. Ipsum vitae temporibus omnis hic incidunt doloremque necessitatibus in dignissimos. Sint error eos illum quibusdam porro ea cupiditate suscipit. Aperiam, voluptas excepturi?
            Itaque architecto tenetur, debitis quos eius amet. Quae autem nemo eum? Iure iusto dicta error eius, quos blanditiis aliquid iste, numquam voluptate soluta libero voluptatibus velit nulla ullam corrupti natus.
            Veniam, quisquam dignissimos non ipsum possimus libero! Saepe recusandae rem cumque, quisquam sit nemo tenetur vitae tempore iure adipisci quibusdam aliquam velit obcaecati, officia nulla rerum quaerat nisi? Natus, consequuntur?
            In ipsa quaerat veniam! Dolorum illo vero aperiam quibusdam. Neque, maxime laborum eligendi sequi consequatur soluta cumque sed maiores vero ad culpa explicabo id ducimus similique ipsum tempora quibusdam magnam.
            Reprehenderit ad quas, reiciendis ipsa explicabo repellendus nulla sed omnis unde accusantium provident ut, necessitatibus hic minima quo earum a? Dolorum unde voluptatibus et, recusandae earum non nesciunt sed tempore.
            accusantium totam similique iste a exercitationem, cumque veniam id molestiae autem harum maiores dignissimos quis saepe nostrum natus sapiente reprehenderit! Quia laborum nulla voluptatibus quaerat.

            <button className="bg-black p-2  text-white " onClick={()=>window.scrollTo({top:0 ,behavior:'smooth' })}>Back to top</button>
</p>
        </div>

    )
}
export default Contact